# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ed7c9376-56c2-403e-9f1a-422125605ceb";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e7cbb2b6-c78d-4b8d-a8bf-82eda631617e".device = "/dev/disk/by-uuid/e7cbb2b6-c78d-4b8d-a8bf-82eda631617e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C7EB-6BE6";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

	swapDevices = [ {
	    device = "/swapfile";
	    size = 8*1024;
	  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
